networks:
  quarkus-net:

services:
  db:
    image: postgres:15
    container_name: quarkus-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-app}
      POSTGRES_PASSWORD: ${DB_PASS:-apppass}
      POSTGRES_DB: ${DB_NAME:-quarkus}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - quarkus-db-data:/var/lib/postgresql/data
    networks:
      - quarkus-net

  adminer:
    image: adminer:5.3.0
    container_name: quarkus-adminer
    restart: always
    ports:
      - "8181:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - quarkus-net

volumes:
  quarkus-db-data:
